# Generated by Django 5.0.3 on 2024-04-25 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graal', '0002_remove_comparison_create_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparison',
            old_name='column',
            new_name='metric',
        ),
    ]
