# Generated by Django 5.0.3 on 2024-04-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graal', '0004_comparison_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparison',
            old_name='change',
            new_name='size_effect',
        ),
    ]
