# Generated by Django 5.0.3 on 2024-05-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graal', '0006_comparison_generated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparison',
            old_name='metric',
            new_name='column',
        ),
    ]
