# Generated by Django 5.0.3 on 2024-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graal', '0007_rename_metric_comparison_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='key',
            field=models.CharField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
