# Generated by Django 5.0.3 on 2024-05-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graal', '0008_comparison_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='real_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
