# Generated by Django 5.0.3 on 2024-05-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graal', '0009_comparison_real_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparison',
            old_name='size_effect',
            new_name='effect_size',
        ),
    ]
