# Generated by Django 5.0.3 on 2024-05-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graal', '0010_rename_size_effect_comparison_effect_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256, unique=True)),
                ('reason', models.TextField()),
            ],
        ),
    ]
